### ISSUE TITLE
Not able to enable TDE on hydra Database

### ISSUE THREAD

**Issue by shah-manthan9** [Percona-Lab/pg_tde#122]
We are using the Hydra Database with version 16. While trying to setup the TDE on our instance we are getting following error
`ERROR: failed to retrieve master key`

I have raised a bug in hydradatabase as well that can seen at :https://github.com/hydradatabase/hydra/issues/241

**Comment by dutow** [comment]
Hello @shah-manthan9 

Both `hyrda` and `tg_tde` are table access methods to postgres, you can't combine the two. You should be able to get `pg_tde` working on the same postgres instance as `hydra`, but you won't be able to create a table that utilizes both.
