### ISSUE TITLE
Dockerhub repo name changed?

### ISSUE THREAD

**Issue by tsaarni** [Percona-Lab/pg_tde#130]
There are references to image [`perconalab/pg_tde`](https://hub.docker.com/r/perconalab/pg_tde) e.g. in the [README](https://github.com/Percona-Lab/pg_tde?tab=readme-ov-file#run-in-docker) but there is no such repo at dockerhub, and I cannot find repo named `pg_tde` under Percona-Lab [github packages](https://github.com/orgs/Percona-Lab/packages?repo_name=pg_tde) either. 

In one of the [blog articles](https://www.percona.com/blog/using-the-transparent-data-encryption-extension-pg_tde-with-postgresql/) I saw [`perconalab/postgres-tde-ext`](https://www.percona.com/blog/using-the-transparent-data-encryption-extension-pg_tde-with-postgresql/) which seems to be the correct one.

**Comment by capri1989** [comment]
Thanks a lot for reporting this @tsaarni. Seems like this fell through the cracks, during the repository rename. We'll look into it and keep you posted

**Comment by dAdAbird** [comment]
Hi @tsaarni, thank for the report. We've fixed the issue and [perconalab/pg_tde](https://hub.docker.com/r/perconalab/pg_tde) image is available now. I'm closing the issue but feel free to re-open it or create a new one should you have any concerns
