### ISSUE TITLE
Create GitHub actions against the latest PG 16 minor release

### ISSUE THREAD

**Issue by capri1989** [Percona-Lab/pg_tde#134]
Create a set of tests against the latest minor release PG 16.2.

If there is a way, to always test against the latest minor release, this would be optimal. Maybe we should go directly with the master branch?

**Comment by dutow** [comment]
@capri1989 I didn't create this issue because I checked and we partially to this already: our completely source code builds are built againts the specific commit we are using, but we also test with the latest pgdg 16 package.

**Comment by capri1989** [comment]
Awesome, didn't know that. So if we do already test against the latest pgdg packages, we can close here.
