### ISSUE TITLE
False positive tap test 002_rotate_key

### ISSUE THREAD

**Issue by dAdAbird** [Percona-Lab/pg_tde#222]
Ttest `pg_tde/002_rotate_key` was “passing” despite a failed rotation (`ERROR:  could not open tde file "pg_tblspc/2139062143/PG_16_202307071/2139062143/pg_tde.map": No such file or directory`). It would fail (as it should have) if substitute ERROR with FATAL or PANIC.

**Comment by ImTheKai** [comment]
Will be tracked here https://perconadev.atlassian.net/browse/PG-837
