### ISSUE TITLE
Documentation for  Streaming Replication

### ISSUE THREAD

**Issue by jobinau** [Percona-Lab/pg_tde#224]
Currently, the documentation page is empty
https://github.com/Percona-Lab/pg_tde/blob/main/documentation/docs/replication.md
Expected to address :
1. how to set up the key provider and master key in the context of physical replication?
2. Is it possible to use the same key provider and master key?
3. If a table on the primary site is encrypted, will all the standby sites also have the encrypted table replicated, given that the same key is implemented on the standby sites as well?

**Comment by ImTheKai** [comment]
Will be tracked here https://perconadev.atlassian.net/browse/PG-838
