### ISSUE TITLE
Test WAL encryption with different options

### ISSUE THREAD

**Issue by dAdAbird** [Percona-Lab/pg_tde#234]
We have to test WAL handling and replication with encrypted WAAL and different WAL settings if changing the parameters doesn't cause some issues. For example changing `wal_buffers` GUC, `--wal-segsize` initdb option and `--with-wal-blocksize` configure option (see https://www.postgresql.org/docs/current/wal-internals.html)

**Comment by ImTheKai** [comment]
Will be tracked here https://perconadev.atlassian.net/browse/PG-840
