### ISSUE TITLE
Error when starting pg_tde: failed to register custom resource manager "test_tdeheap_custom_rmgr"

### ISSUE THREAD

**Issue by tsaarni** [Percona-Lab/pg_tde#260]
I wanted to test pg_tde with an existing application on Kubernetes, so I replaced the Postgres deployment with latest pg_tde image ([link](https://hub.docker.com/r/perconalab/pg_tde)). It seems that the container attempts to enable the pg_tde extension by default ([link](https://github.com/Percona-Lab/pg_tde/blob/main/docker/pg-tde-create-ext.sh#L7)) but this doesn't actually work. The functions are unavailable until I manually run `CREATE EXTENSION pg_tde;`.

When the Postgres pod starts for the first time I notice an error in the logs.

> failed to register custom resource manager "test_tdeheap_custom_rmgr" with ID 128

The pod fails and restarts. On subsequent restarts, the error doesn't appear, but I suspect it might be because of following (as mentioned in [postgres container documentation](https://hub.docker.com/_/postgres))

> Warning: scripts in /docker-entrypoint-initdb.d are only run if you start the container with a data directory that is empty; any pre-existing database will be left untouched on container startup. One common problem is that if one of your /docker-entrypoint-initdb.d scripts fails (which will cause the entrypoint script to exit) and your orchestrator restarts the container with the already initialized data directory, it will not continue on with your scripts.

<details>

<summary>Full logs</summary>

```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2024-08-13 15:34:31.922 UTC [55] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-08-13 15:34:31.929 UTC [55] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-08-13 15:34:31.949 UTC [58] LOG:  database system was shut down at 2024-08-13 15:34:31 UTC
2024-08-13 15:34:31.958 UTC [55] LOG:  database system is ready to accept connections
 done
server started
2024-08-13 15:34:32.026 UTC [64] LOG:  statement: SELECT 1 FROM pg_database WHERE datname = 'keycloak' ;
2024-08-13 15:34:32.049 UTC [66] LOG:  statement: CREATE DATABASE "keycloak" ;
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/pg-tde-create-ext.sh
2024-08-13 15:34:32.120 UTC [68] LOG:  statement: CREATE EXTENSION pg_tde;
WARNING:  pg_tde can only be loaded at server startup. Restart required.
ERROR:  failed to register custom resource manager "test_tdeheap_custom_rmgr" with ID 128
DETAIL:  Custom resource manager must be registered while initializing modules in shared_preload_libraries.
2024-08-13 15:34:32.122 UTC [68] WARNING:  pg_tde can only be loaded at server startup. Restart required.
2024-08-13 15:34:32.122 UTC [68] LOG:  Initializing TDE principal key info
2024-08-13 15:34:32.122 UTC [68] STATEMENT:  CREATE EXTENSION pg_tde;
2024-08-13 15:34:32.122 UTC [68] LOG:  initializing TDE key provider info
2024-08-13 15:34:32.122 UTC [68] STATEMENT:  CREATE EXTENSION pg_tde;
2024-08-13 15:34:32.122 UTC [68] ERROR:  failed to register custom resource manager "test_tdeheap_custom_rmgr" with ID 128
2024-08-13 15:34:32.122 UTC [68] DETAIL:  Custom resource manager must be registered while initializing modules in shared_preload_libraries.
2024-08-13 15:34:32.122 UTC [68] STATEMENT:  CREATE EXTENSION pg_tde;
```

</details>

<details>
<summary>Kubernetes manifest I used to run pg_tde</summary>

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgresql
          image: perconalab/pg_tde
          args:
            - "-c"
            - "log_statement=all"
            - "-c"
            - "log_destination=stderr"
          env:
            - name: POSTGRES_USER
              value: "keycloak"
            - name: POSTGRES_PASSWORD
              value: "keycloak"
            - name: POSTGRES_DB
              value: "keycloak"

          ports:
            - name: postgres
              containerPort: 5432

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"

```

</details>

**Comment by dAdAbird** [comment]
Hi @tsaarni, thanks for the report.

Yes, looks like `CREATE EXTENSION pg_tde;` during container start don't work `-e POSTGRES_DB`. Probably db is being created before  the init script run. Nevertheless, manual application `CREATE EXTENSION pg_tde;` should work and it does for me with just docker. Tbh, we haven't tested it k8s yet. So anything possible...
I think subsequent starts' succeess (rather the first's fail) are due to "WARNING:  pg_tde can only be loaded at server startup. Restart required." - extension lib being loaded late. We'll investigate why this happens. 

Can you clarify your exact steps around "... until I manually run CREATE EXTENSION pg_tde;"?

The line in logs:
```
2024-08-13 15:34:32.120 UTC [68] LOG:  statement: CREATE EXTENSION pg_tde;
```
This is you running `CREATE EXTENSION pg_tde;` in psql console?

Cheers!

**Comment by tsaarni** [comment]
@dAdAbird wrote
> This is you running CREATE EXTENSION pg_tde; in psql console?

No, that was what the container printed at initial start with SQL statement debug enabled. 

I think those lines are coming as result of executing the [script from base image](https://github.com/docker-library/postgres/blob/805329e7a64fad212a5d4b07abd11238a9beab75/16/bookworm/docker-ensure-initdb.sh#L49) that runs `/docker-entrypoint-initdb.d/*`. It runs the initdb script in pg_tde image where the statement is https://github.com/Percona-Lab/pg_tde/blob/9cf87a47d20475c9556e4bac1871a305b5f049a7/docker/pg-tde-create-ext.sh#L7-L8
I think subsequent starts succeed because the base image does not run the initdb scripts if [database directory already exists](https://github.com/docker-library/postgres/blob/805329e7a64fad212a5d4b07abd11238a9beab75/16/bookworm/docker-ensure-initdb.sh#L33) - which apparently does exist in subsequent restarts.  This is reflected by logs at next restart

```
PostgreSQL Database directory appears to contain a database; Skipping initialization
```

This seems be what the warning in Postgres dockerhub image readme also said, which I copied [above.](https://github.com/Percona-Lab/pg_tde/issues/260#issue-2463694734)

**Comment by tsaarni** [comment]
I figured out what my problem was! 

In original postgres container the command in Dockerfile is `CMD ["postgres"]` while in pg_tde the command is `CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]`. 

When I pass arguments to postgres in my Kubernetes manifest, I need to include `-c config_file=/etc/postgresql/postgresql.conf` too. Apparently by default the config file is something else (or no config file is loaded at all)  which meant `shared_preload_libraries = 'pg_tde'` was not taking effect - causing the errors above.

Sorry for the trouble!
