### ISSUE TITLE
Add tests for streaming replication

### ISSUE THREAD

**Issue by dAdAbird** [Percona-Lab/pg_tde#60]
Need to spin up replica env and run basic `INSERT`, `UPDATE`, `DELETE` and `COPY <table> FROM` scenarios.
See `multi_insert` tests for `COPY ... FROM` (https://github.com/Percona-Lab/pg_tde/blob/main/sql/multi_insert.sql)
And `insert_update_delete` tests for  `INSERT`, `UPDATE`, `DELETE`  (https://github.com/Percona-Lab/pg_tde/blob/main/sql/insert_update_delete.sql)

**Comment by ImTheKai** [comment]
Will be tracked here https://perconadev.atlassian.net/browse/PG-815
