### ISSUE TITLE
TDE fork for relation created by the aborted transaction gets shipped to standby side

### ISSUE THREAD

**Issue by codeforall** [Percona-Lab/pg_tde#65]
```
BEGIN;
create table to_rollback( a int, b text) using pg_tde ;
insert into to_rollback values ( 4,'four'), (5,'five'), (6, 'six');
rollback ;

```
Executing this test case ships the tde fork files to standby even when the transaction was aborted.

**Comment by dAdAbird** [comment]
@EngineeredVirus :
```
Test:
(1) Explicit Transaction Block
(2) Prepared Transaction
(3) Rolling back to an earlier savepoint
```

**Comment by dAdAbird** [comment]
@codeforall: check if we can rewrite map file

**Comment by codeforall** [comment]
We have changed the design around storing the relation keys, and the extension no longer creates the relation file. So, this issue is no longer valid.
