### ISSUE TITLE
Performance issue with JSONB and JSON fields

### ISSUE THREAD

**Issue by waltton** [Percona-Lab/pg_tde#89]
I ran some tests that I had prepared to compare the performance of different datatypes and saw that JSONB performance is around 2.5x lower and JSON 1.5x lower.

The code I used to run the test is available here: https://github.com/waltton/pg_json_bench/tree/pg_tde
(there is a branch with a couple of changes to support `pg_tde`)

It runs:
```SQL
SELECT COUNT(*) FROM %s WHERE CAST(data->>'score' AS FLOAT) > 7.0
```

The table that is used could have a column as JSON or JSONB, using heap or pg_tde as access method.

The data comes from https://raw.githubusercontent.com/algolia/datasets/master/movies/records.json and each item in the array goes to one row in the db.

<img width="1470" alt="image" src="https://github.com/Percona-Lab/postgres-tde-ext/assets/4743160/a1e475ae-82f5-4500-ae02-4ffd44141fab">

**Comment by waltton** [comment]
To add to the initial message, the tests I did ran on my Macbook Air with M2 using docker.

Also, run the test for insert speed, which looks quite good. (It was a very small test with only a few iterations)

<img width="1452" alt="Screenshot 2023-12-15 at 1 24 47 PM" src="https://github.com/Percona-Lab/postgres-tde-ext/assets/4743160/d2393df0-6886-4504-b925-b96e75b3077d">

**Comment by dutow** [comment]
Thanks for the report @waltton, I was able to verify the performance drop.

One small correction, in the description and in the readme file for pg_json_bench, I think you wanted to link https://raw.githubusercontent.com/algolia/datasets/master/movies/movies.json ? That repository doesn't have a records.json there.
